### ISSUE TITLE
How do I add a building in a mod?

### ISSUE THREAD

**Issue by jazzpi** [SFTtech/nyan#10]
There aren't any references to buildings in the mods in the examples and I can't figure it out. Does the engine just add all buildings it reads in a mod file automatically or do you need to patch villagers to allow them to create them or something?

**Comment by TheJJ** [comment]
If you add a new building in a mod, you have to patch the villager to be able to create it.

``` python

# some new building that can create villagers
NewBuilding(Building):
    cost = 300
    creates = {Villager}

AddNewBuilding<Villager>():
    creates += {NewBuilding}

AwesomeMod(Mod):
    name = "blabla"
    patches = {AddNewBuilding}
```

**Comment by TheJJ** [comment]
We should add something like that as an example about buildings. Could you understand it?
