### ISSUE TITLE
Releasing a new version?

### ISSUE THREAD

**Issue by duanqn** [SFTtech/nyan#108]
Hi I noticed that the Windows build pipeline for openage is failing right now so I'd like to remedy that.
To make it easier to maintain in the long run, I think it is the best to integrate nyan into vcpkg so that its dependencies and build status can be tracked.
I have submitted a port request on vcpkg side. Do you have plans to release a new version recently? The vcpkg people may want to use existing github releases instead of the latest commit on master branch.

**Comment by duanqn** [comment]
Working on this PR: https://github.com/microsoft/vcpkg/pull/32250

**Comment by heinezen** [comment]
Hi, I think this is a pretty good idea!

https://github.com/SFTtech/nyan/pull/106 would result in a version bump / new release so this would be good time for packaging. It will probably be merged alongside https://github.com/SFTtech/openage/pull/1515 which is still a 1-2 weeks away from completion. However, it would be a relatively stable release for use in openage.

**Comment by duanqn** [comment]
Hi @heinezen , when porting the current nyan to vcpkg I got this error:
```
warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    D:\packages\nyan-lang_x86-windows\bin\nyancat.exe

warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    D:\packages\nyan-lang_x86-windows\debug\bin\nyancat.exe
```

Is this nyancat.exe (on Windows) necessary for nyan?

**Comment by duanqn** [comment]
Got it. Thanks. I'll see if I can register it as "tools". If not, I'll remove it.

**Comment by heinezen** [comment]
@duanqn New release is pushed and should be ready.

**Comment by TheJJ** [comment]
`nyancat` was intended as a formatter/check/print/coloring tool, but right now it's just for testing validity. so for packaging we currently don't need it, but it may be useful later if we add the features. if vcpkg has no `nyan` package so far, i'd favor naming it `nyan` instead of `nyan-lang`, since it will contain `nyan.dll` etc and not `nyan-lang.dll`.

**Comment by duanqn** [comment]
Hi @TheJJ , I will put `nyancat` in the vcpkg package as a tool binary.
As for the name of the package. I'm using `nyan-lang` because vcpkg favors the name from [repology](https://repology.org/). Looks like this nyan is called `nyan-lang` and `nyan` points to https://github.com/shibumi/nyan.

**Comment by duanqn** [comment]
> @duanqn New release is pushed and should be ready.

Got it. Will update to 0.3.0 on vcpkg side.

**Comment by duanqn** [comment]
Hi @TheJJ , there are build failures on UWP. Can you have a look?
[install-x64-uwp-dbg-out.log](https://github.com/SFTtech/nyan/files/11945188/install-x64-uwp-dbg-out.log)

Also, all static linkage builds failed because nyan produces dynamic libs. If we don't want to support static libs, I can disable the static builds.

**Comment by duanqn** [comment]
Also the build failed on OSX. I don't understand the errors. Looks like an issue with the compiler?
[install-x64-osx-dbg-out.log](https://github.com/SFTtech/nyan/files/11945415/install-x64-osx-dbg-out.log)

**Comment by heinezen** [comment]
> Also the build failed on OSX. I don't understand the errors. Looks like an issue with the compiler?

@duanqn AppleClang is notorious for being out-of-date, so maybe that's where the problems come from? Can you try normal clang and check if that works out? Just tested it with the current build on Ubuntu and it compiles fine in Clang 15.

**Comment by duanqn** [comment]
@heinezen Could be. However, I cannot change the clang version in their build pipelines. I'm going to disable OSX build (until their compiler catches up with everyone else).

**Comment by heinezen** [comment]
> @heinezen Could be. However, I cannot change the clang version in their build pipelines because it should represent the reality of OSX... I'm going to disable OSX build (until their compiler catches up with everyone else).

Understandable but frustrating. AppleClang is now 2 standards behind with this.

**Comment by duanqn** [comment]
@heinezen Meanwhile, can you check the UWP build errors?
Also, do we plan to support a static library build?

**Comment by TheJJ** [comment]
adding a static library option is simple, what would we need it for? i like dynamic linking :)

**Comment by duanqn** [comment]
Looks like the UWP failure is because SymInitialize does not exist in UWP. Any ideas on how to fix it?

**Comment by heinezen** [comment]
@duanqn As far as I understand it, there's no equivalent and UWP simply does not allow most debug thing to be build. So we have to check for the UWP build and remove the dbghelp.h references entirely.

**Comment by heinezen** [comment]
https://cmake.org/cmake/help/latest/variable/WINDOWS_STORE.html seems to inducate UWP support

**Comment by duanqn** [comment]
FYI, I have added nyan to vcpkg via https://github.com/microsoft/vcpkg/pull/32250 .

**Comment by heinezen** [comment]
nicely done :)
