### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by kennymalac** [SFTtech/nyan#11]
Hey I want to use this.
I am making a game engine in C++17, and I need a way of dynamically interacting with objects. I'm considering adding scripting in Common Lisp but I'd like a C++ API (perhaps with CFFI support)
Is there any way I can help? I started on a Query system in https://github.com/kennymalac/game/blob/master/space.cpp

I'm still unsure of some details but I figure I'd want the Query system in my engine to be pretty similar to what would be used in the modding API.

**Comment by TheJJ** [comment]
It totally is in use, it's my masters thesis, currently ongoing :)
Best help for now would be to look at the specification in `doc/nyan.md` and see if the design has flaws. The implementation in C++14/17? is missing a lot of things but I'll be working full-time on this until ~September.

**Comment by TheJJ** [comment]
For further question, just reply here or join our IRC/Matrix chat pls.
