### ISSUE TITLE
Add metaclass like python

### ISSUE THREAD

**Issue by coco875** [SFTtech/nyan#113]
It will be interesting if you can make some metaclass like (also this syntax is if function in nyan are the same declaration then python etc)
```python
Health:
  _hp = 0
  _shield = 10 // the shield don't regen
  function __get__():
    return _hp

  function __set__(value):
    _hp = value

  function __add__(value):
    _hp += value

  function __sub__(value):
    if _shield < 0:
      _hp -= value
    else:
      _shield -= value

Strider(Unit):
    hp = Health
    hp = 10
    hp += 10 // so now hp == 20
    hp -= 10 // hp still 20 because shield
    hp -= 5 // hp == 15 because shield is below 0
    animation = "./assets/strider.ani"
```

(I use the keyword function because when I wrote it earlyer I doing lua but he can be a good feature)

**Comment by TheJJ** [comment]
This looks interesting, but I fear this is not suitable for nyan - it is explicitly not a turing-complete programming language, but rather a data description language. When "real" scripting is needed, one should rather use Python, Lua, C++ for describing the logic, and then accessing nyan for fetching the data values and objects for configuring the logic.

**Comment by coco875** [comment]
so the moddable API is going throught python api call so like
nyan who include python to define function
```python
import custom_mod

cls:
  __add__ = custom_mod
```
or vice-versa in python
```python
import nyan_file

def nyan_file.cls.__add__:
  ...
```

**Comment by coco875** [comment]
but if nyan don't have logic this also mean he don't have function so how implent it ?

**Comment by TheJJ** [comment]
You have your "regular" lua, python or c++ game engine. But instead of reading data from yaml files, you load them from nyan. That way you have more potent data description feature, but all the regular programming features (functions, loops, variables, ...) remain in languages way more suitable for programming than we would ever be able to implemennt in nyan.

**Comment by TheJJ** [comment]
I'll go ahead and close this request for now, if you have questions about nyan's design and how to use it, please come by in our matrix chatroom for a more interactive chat :)
