### ISSUE TITLE
Add decorator like python

### ISSUE THREAD

**Issue by coco875** [SFTtech/nyan#114]
I think adding decorator like python to make event for modding like

```python
@on_unit_spawn
function add_particle(u:Unit):
  Game.spawn_particule(deflaut, u.x, u.y)
```
so now every time a unit spawn the function add_particle is called (and you can optimise event by lauching it in multithread)

**Comment by TheJJ** [comment]
as said in #113 nyan is not supposed to be a programming language, but rather describes the data. so having decorators would be something used in your python script, which accesses data stored in nyan.
