### ISSUE TITLE
nyan -> common notation format converter

### ISSUE THREAD

**Issue by coffenbacher** [SFTtech/nyan#12]
I'm writing a very stripped down version of the aoe2 engine in javascript for some purposes, but I don't want to write a parser just to use nyan files :'( If someone wrote a nyan -> json or something, that would be awesome :D

**Comment by TheJJ** [comment]
I'm sorry but this is rather impossible.

Converting `nyan` files to json is `trivial` (just nested key-value pairs), the interesting part is the typing and execution logic on top of that.
Which means you'd have to rewrite the nyan database as a whole in js.
