### ISSUE TITLE
Getting a CMake Error on FLEX_INCLUDE_DIR

### ISSUE THREAD

**Issue by cmlccie** [SFTtech/nyan#22]
I'm getting the following error when attempting to build nyan:
``` bash
build [master]$ cmake ..


       ▄▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▄
       █░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░█
       █░▒▒▒▒▒▒▒▒▒▒▄▀▀▄▒▒▒░░█▄▀▀▄
  ▄▄   █░▒▒▒▒▒▒▒▒▒▒█▓▓▓▀▄▄▄▄▀▓▓▓█      ▄ ▄▄   ▄   ▄   ▄▄▄   ▄ ▄▄
█▓▓█▄▄█░▒▒▒▒▒▒▒▒▒▄▀▓▓▓▓▓▓▓▓▓▓▓▓▀▄      █▀  █  ▀▄ ▄▀  ▀   █  █▀  █
 ▀▄▄▓▓█░▒▒▒▒▒▒▒▒▒█▓▓▓▄█▓▓▓▄▓▄█▓▓█      █   █   █▄█   ▄▀▀▀█  █   █
     ▀▀█░▒▒▒▒▒▒▒▒▒█▓▒▒▓▄▓▓▄▓▓▄▓▒▒█     █   █   ▀█    ▀▄▄▀█  █   █
      ▄█░░▒▒▒▒▒▒▒▒▒▀▄▓▓▀▀▀▀▀▀▀▓▄▀              ▄▀
    ▄▀▓▀█▄▄▄▄▄▄▄▄▄▄▄▄██████▀█▀▀               ▀▀
    █▄▄▀ █▄▄▀       █▄▄▀ ▀▄▄█


For information about building, look at [doc/building.md].

If you encounter problems you can't fix yourself,
report problems at https://github.com/SFTtech/nyan

Contact: #sfttech:matrix.org

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
CMake Warning at buildsystem/doxygen.cmake:50 (message):
  doxygen couldn't be found, you won't be able to generate docs
Call Stack (most recent call first):
  CMakeLists.txt:78 (doxygen_configure)


-- registering nyan in the cmake user package registry (~/.cmake/package/nyan)...

          project | nyan
          version | 1.0
         compiler | AppleClang 9.0.0.9000039
       build type | Debug
         cxxflags |  -Wall -Wextra -pedantic
 build type flags | -O0 -ggdb3
        build dir | /Users/user/dev/sandbox/nyan/build
   install prefix | /usr/local

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/Users/user/dev/sandbox/nyan/nyan/FLEX_INCLUDE_DIR
   used as include directory in directory /Users/user/dev/sandbox/nyan/nyan

-- Configuring incomplete, errors occurred!
See also "/Users/user/dev/sandbox/nyan/build/CMakeFiles/CMakeOutput.log".
```
I do have flex installed.  I am using a Mac.  I am following the build instructions.

I don't see a reference to the the **`FLEX_INCLUDE_DIR`** variable in source repo.  The only reference I see is to `FLEX_INCLUDE_DIRS` in `CMakeLists.txt`:
```
# include directory specification
# depending if nyan was built or installed,
# projects using libnyan will automatically include the correct dir.
target_include_directories(nyan
	PUBLIC
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/../>
		$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/>
	PRIVATE
		${FLEX_INCLUDE_DIRS}
)
```

**Comment by cmlccie** [comment]
Manually setting a `FLEX_INCLUDE_DIR` to the path to the flex include directory doesn't change the error.

**Comment by tusharpm** [comment]
You can try to set `FLEX_INCLUDE_DIRS` manually, in case CMake failed to find it automatically.
`FLEX_INCLUDE_DIR` is internal to CMake. [`FindFLEX` module defines `FLEX_INCLUDE_DIRS`](https://cmake.org/cmake/help/latest/module/FindFLEX.html) as the external variable.

**Comment by nyx** [comment]
@cmlccie I ran into this as well on macOS literally yesterday. I had installed flex v2.6.4 (which was another gotcha, the system version is not new enough and the generated code uses deprecated `register` qualifier for C++17 standard. Anyway after I `brew install flex`, I ended up adding that to the the head of my `PATH` environment variable as Homebrew suggested so it's supercede the system one as explicitly setting it in CMake apparently isn't respected everywhere, I then did `brew info` again and it gives you the `LDFLAGS` and `CPPFLAGS` to use for builds. I grabbed those and threw them into the `CMake` configuration.

```
 FLEX_EXECUTABLE                  /usr/local/opt/flex/bin/flex                                                                             
 FLEX_INCLUDE_DIR                 /usr/local/opt/flex/include                                                                              
 FL_LIBRARY                       /usr/local/opt/flex/lib/libfl.dylib 
```

**Comment by tusharpm** [comment]
Yes, the system version is `flex 2.5.35 Apple(flex-31)` on macOS 10.13.2 High Sierra. The change removing `register` is in release 2.6.0, which can be called the minimum required flex version for the project.
Specifying the `FLEX_EXECUTABLE` and `FLEX_INCLUDE_DIR` on the cmake command line suffices. The `PATH` can be left unmodified. It works without setting `FL_LIBRARY` for now; however, it might be a good idea to set that also - in case we add it as nyan's link dependency in the future.
I got a linker error afterwards for using `-Wl,--no-undefined`.
I've captured the relevant changes in #25. Please have a look at the PR and provide your review comments.

**Comment by TheJJ** [comment]
Please report back if you still encounter problems.
