### ISSUE TITLE
Missing AX_CXX_COMPILE_STDCXX_14 macro

### ISSUE THREAD

**Issue by iNaKoll** [SFTtech/nyan#6]
The `AX_CXX_COMPILE_STDCXX_14` used in `./configure.ac` **might or should** be provided by the `autoconf-archive` system package in the file `ax_cxx_compile_stdcxx_14.m4` installed system wide.

There is actually three probem with this : 
1. The `autoconf-archive` is not in the dependency list in `doc/building.md`
2. The file is [present](https://www.archlinux.org/packages/community/any/autoconf-archive/) in the Arch Linux package but is [absent](http://packages.ubuntu.com/xenial/all/autoconf-archive/filelist) in the Ubuntu (16.04) package.
3. The file `ax_cxx_compile_stdcxx_14.m4` depends on `ax_cxx_compile_stdcxx.m4` which is also missing from Debian based `autoconf-archive` package.

Workaround : install manually the files [ax_cxx_compile_stdcxx_14.m4](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cxx_compile_stdcxx_14.m4) and [ax_cxx_compile_stdcxx.m4](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cxx_compile_stdcxx.m4) in the `./m4` folder.

**Comment by TheJJ** [comment]
Hm yes, you're right. But shipping those files seems to be bad duplication, so I'm thinking of either ignoring distros not providing the files, or hardcoding `-std=c++14` again or switching to cmake..
what do you think?
