### ISSUE TITLE
Let objects be declared as abstract even if they contain no members

### ISSUE THREAD

**Issue by heinezen** [SFTtech/nyan#61]
According to the specification, nyan objects "remain abstract until all members have values"  ("A `nyan::Object` is "abstract" iff it contains at least one undefined member"). Some of the openage API objects would require objects to be abstract that contain no members. These objects are often used as generalization objects that should be inherited from, but not be used on their own.

Examples : `GameEntityType`, `DiplomaticStance`, `TradeRoute`, `DropoffType`

Proposed solution: Use the same idea as in #58 and introduce parameters for sets. In this case the definition could look like this: `set(typename, only_children=True)`

For single references, use a new `child` container type: `child(typename)`

**Comment by TheJJ** [comment]
If the generalization objects don't add any member, why are they needed then?

**Comment by heinezen** [comment]
Mostly, modders are expected to inherit from the generalization object for a specialized case and not use the generalization object itself. For example, in AoE2 we derive the stances `Enemy`, `Neutral`, `Ally` from `DiplomaticStance` which is used in `DiplomaticAbility`:

```
DiplomaticAbility(engine.Ability):
diplomatic_stances : set(engine.DiplomaticStance)
```

It should only be possible to add `Enemy`, `Neutral`, `Ally` and not `engine.DiplomaticStance`.

**Comment by TheJJ** [comment]
And `DiplomaticStance` doesn't add any new (undefined) members? If it does, I think it would be better to allow any other child object there, e.g. if a mod adds another stance like `TradePartner` which is still an enemy but you can trade with. If it doesn't, what there's surely a common parent object that can be used instead?

**Comment by heinezen** [comment]
We agreed to introduce a new `only_children` parameter for sets, similar to #58. In the set declaration this parameter is optional and can be either true or false.

Example:
```
DiplomaticAbility(Ability):
stances : set(DiplomaticStance, only_children=True)
```

**Comment by heinezen** [comment]
Turns out this only solves the problem for sets. We have situations in the API where a member has the `nyan::Object` type, but only its children should be referenced. 

Example:
```
FlatAttributeChange(ContinuousEffect):
    type              : AttributeChangeType
    min_change_rate   : optional(AttributeRate)
    max_change_rate   : optional(AttributeRate)
    change_rate       : AttributeRate
    ignore_protection : set(ProtectingAttribute)
```

The `type` member should only be allowed to reference children of `AttributeChangeType`.

**Comment by TheJJ** [comment]
Possible solution: Another container type like `childs`, which behaves similar to `optional`, but enforces that only child objects are assigned:

```
type : childs(AttributeChangeType)
```

**Comment by TheJJ** [comment]
I've created  #65 to track this feature.
