### ISSUE TITLE
children(type) to allow children only

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/nyan#65]
This is a new type that matches to objects that are child of the given type.
This is useful for e.g. describing this case:
``` python
DiplomaticAbility(Ability):
    stances : set(children(DiplomaticStance))
```

The `DiplomaticStance` is a non-abstract API object, and therefore is valid to be used on its own as a value for stance. As we only want to allow children, the `children(DiplomaticStance)` matches to that.

This implements preventing "too abstract" objects from being used.

**Comment by heinezen** [comment]
I would suggest the following syntax

``` python
DiplomaticAbility(Ability):
    stances : set(DiplomaticStance, onlychilds=True)
```

We could pass an arbitrary number of additional parameters or flags to complex types this way. It would probably work for objects too:

``` python
SomeObject():
    some_member : OtherObject(onlychilds=True)
```

We don't even have to define `childs` as keyword this way.

**Comment by TheJJ** [comment]
This was an earlier thought, but for the type checker it's easier to define `children(something)`. We can use the keyword arguments for other things, but this I think can be done better by nesting types.

**Comment by TheJJ** [comment]
Done in #87.
