### ISSUE TITLE
Commas

### ISSUE THREAD

**Issue by MaanooAk** [SFTtech/nyan#71]
Commas between a collection elements and parents are not needed in order for the nyan to be interpreted. So they could be optional.

``` python
LeggedCombineCitadel(Building, Unit):
    hp = 1000
    creates = {OverwatchSoldier, Strider}

LeggedCombineCitadel(Building, Unit):
    hp = 1000
    creates = { OverwatchSoldier Strider }

LeggedCombineCitadel ( Building Unit ) :
    hp = 1000
    creates = { OverwatchSoldier Strider }
```

It looks weird but why not...

**Comment by TheJJ** [comment]
I've done it the same way Python formats sets, but you are right, it would still be valid.
If we add this feature, the parser should enforce one valid style per set: Within one set either all commas must be there, or none.

I'm not sure though if leaving out commas makes usage easier here, but I guess for non-programmers it could be good.

**Comment by heinezen** [comment]
Not sure about this because it could lead to more semantic errors being made.

```
Barracks(Building):
    hp = 1000
    creates = { CavalryArcher }
```
and 
```
Barracks(Building):
    hp = 1000
    creates = { Cavalry Archer }
```
would both be valid syntax and if there's a mistake here, it's easy to overlook. The commas somewhat mitigate this.

Also, I guess that having two possible styles is a bit irritating for modders or non-programmers.

**Comment by TheJJ** [comment]
I think we should try to be compatible to the python/c++ syntax, so I'll close this proposal for now.
We can reconsider of course if we discover this (or a variation) is needed again.
