### ISSUE TITLE
Allow operations with float values for int data type

### ISSUE THREAD

**Issue by heinezen** [SFTtech/nyan#83]
Currently, the `int` data type operations only allow integers as operands. This limits operations on `int` members somewhat, especially for multiplications.

`int` operations other than `=` should also allow floats to be used as operands. The result of the operation should be typecast internally to `int`, i.e. the resulting value is floored.

```python
SomeObject():
    member : int = 4
    other_member : int = 9

Patch<SomeObject>():
    member *= 2.5f       # result: member = 10  (multiplication: 4 * 2.5 = 10.0 -> 10)
    other_member *= 1.5f # result: c = 13       (multiplication: 9 * 1.5 = 13.5 -> 13)
```

**Comment by TheJJ** [comment]
Done in #87.
