### ISSUE TITLE
v0.1 tag failed to compile on Windows

### ISSUE THREAD

**Issue by duanqn** [SFTtech/nyan#89]
The latest code on master compiles fine. Is it possible to publish a newer tag, or move the v0.1 tag to a "good" commit?

**Comment by duanqn** [comment]
Also, after I compiled the latest code, I got a "nyancat.exe". But I can't figure out what it is.

**Comment by heinezen** [comment]
`nyancat` is the testing suite for the library. Basically a bunch of test cases.

I'll check the Windows build, but I'm not that familiar with Windows, so I'll see what I can do!

**Comment by duanqn** [comment]
The errors are not Windows-specific. They are C++ syntax errors :/

e.g.
nyan\error.h(76): error C2039: 'runtime_error': is not a member of 'std'
nyan\error.h(76): error C2504: 'runtime_error': base class undefined
nyan\c3.cpp(132): error C2065: 'not': undeclared identifier
nyan\c3.cpp(132): error C2146: syntax error: missing ')' before identifier 'candidate_ok'
nyan\c3.cpp(132): error C2143: syntax error: missing ';' before '{'

The latest code compiles fine. I think adding a new tag is good enough.

**Comment by heinezen** [comment]
Sry for the delay. We created a new release for the latest master :)

https://github.com/SFTtech/nyan/releases/tag/v0.1.1

**Comment by TheJJ** [comment]
I guess the error was a missing include so `std::runtime_error` wasn't defined. should be good with the new tag?
